import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./index.css";
import { Suspense } from "react";
import LoadingComponent from "@/components/ui/loadingComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<InterviewLoading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}

function InterviewLoading() {
  return (
    <div className="min-h-screen flex items-center justify-center">
      <LoadingComponent text="Loading..." />
    </div>
  );
}